### ISSUE TITLE
Angular form messages scripts reference src instead of dist.

### ISSUE THREAD

**Issue by RRMoelker** [xebia/angular-form-messages-example#13]
When running `grunt serve` for a clean clone of the repo the following file can not be found by the browser:

```
GET http://localhost:9000/bower_components/angular-form-messages/src/afModule.js 
localhost/:27 GET http://localhost:9000/bower_components/angular-form-messages/src/afMessages.js 
localhost/:28 GET http://localhost:9000/bower_components/angular-form-messages/src/bootstrap/afModule.js 
localhost/:29 GET http://localhost:9000/bower_components/angular-form-messages/src/bootstrap/afFeedback.js 
localhost/:30 GET http://localhost:9000/bower_components/angular-form-messages/src/bootstrap/afFieldState.js 
localhost/:31 GET http://localhost:9000/bower_components/angular-form-messages/src/bootstrap/afMessages.js 
localhost/:32 GET http://localhost:9000/bower_components/angular-form-messages/src/bootstrap/templateCache.js 
localhost/:33 GET http://localhost:9000/bower_components/angular-form-messages/src/afField.js 
localhost/:34 GET http://localhost:9000/bower_components/angular-form-messages/src/afSubmit.js 
localhost/:35 GET http://localhost:9000/bower_components/angular-form-messages/src/afMessageLabel.js 
localhost/:36 GET http://localhost:9000/bower_components/angular-form-messages/src/afSubmitButton.js 
localhost/:37 GET http://localhost:9000/bower_components/angular-form-messages/src/afMessageService.js 
localhost/:38 GET http://localhost:9000/bower_components/angular-form-messages/dist/afMessageService.js 
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module angularFormMessagesExample due to:
Error: [$injector:modulerr] Failed to instantiate module angularFormMessagesBootstrap due to:
Error: [$injector:nomod] Module 'angularFormMessagesBootstrap' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.4/$injector/nomod?p0=angularFormMessagesBootstrap
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:68:12)
    at http://localhost:9000/bower_components/angular/angular.js:1983:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1907:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:1981:14)
    at http://localhost:9000/bower_components/angular/angular.js:4385:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4369:5)
    at http://localhost:9000/bower_components/angular/angular.js:4386:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4369:5)
http://errors.angularjs.org/1.4.4/$injector/modulerr?p0=angularFormMessages…2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4369%3A5)
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:68:12)
    at http://localhost:9000/bower_components/angular/angular.js:4408:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4369:5)
    at http://localhost:9000/bower_components/angular/angular.js:4386:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4369:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4294:11)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1655:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1676:12)
http://errors.angularjs.org/1.4.4/$injector/modulerr?p0=angularFormMessages…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1676%3A12)
```

**Comment by RRMoelker** [comment]
Solved in PR #15

**Comment by fvanwijk** [comment]
You are right but since this example project is not yet ready I'd like to use the src files for debugging. You can check out angular-form-messages and use bower link to have the local repo as dependency.
So for now I do not yet want to merge thus PR unless there becomes a solution to make debugging src easier (without unignoring the src files).

**Comment by fvanwijk** [comment]
I will fix this soon by using source maps

**Comment by RRMoelker** [comment]
For now solve it with PR #21 ?

**Comment by fvanwijk** [comment]
`dist` files are included again. The source is available via source maps. Everything should work out of the box.

`bower link` is not possible anymore and `npm link` is only advised while developing. Since this a general pattern when simultaneously developing on a dependency/example project, I find it not necessary to include the comment anymore.
